spring:
  application:
    name: client-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

